project_id = "kpynatdltoakbpwbjxqm"

[functions.sitemap]
verify_jwt = false

[functions.prerender]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.prerender-middleware]
verify_jwt = false