import { Helmet } from 'react-helmet-async';
import { Tool } from '@/data/tools';

interface AdvancedMetaTagsProps {
  title: string;
  description: string;
  url: string;
  type?: 'website' | 'article' | 'product';
  image?: string;
  imageWidth?: number;
  imageHeight?: number;
  imageAlt?: string;
  publishedTime?: string;
  modifiedTime?: string;
  author?: string;
  section?: string;
  tags?: string[];
  tool?: Tool;
}

/**
 * Advanced Meta Tags Component
 * Comprehensive OG, Twitter Card, and social media meta tags
 */
const AdvancedMetaTags = ({
  title,
  description,
  url,
  type = 'website',
  image,
  imageWidth = 1200,
  imageHeight = 630,
  imageAlt,
  publishedTime,
  modifiedTime,
  author = 'ToolsML Editorial Team',
  section,
  tags = [],
  tool
}: AdvancedMetaTagsProps) => {
  const baseUrl = 'https://ai-toolsml.lovable.app';
  const fullUrl = url.startsWith('http') ? url : `${baseUrl}${url}`;
  
  // Generate dynamic OG image URL based on content
  const generateDynamicImage = (): string => {
    if (image) return image.startsWith('http') ? image : `${baseUrl}${image}`;
    
    // Default OG image with better fallback
    if (tool) {
      // Tool-specific image (would be generated by OG image service in production)
      return `${baseUrl}/og-image.jpg?title=${encodeURIComponent(tool.title)}&category=${tool.category}`;
    }
    
    return `${baseUrl}/og-image.jpg`;
  };

  const ogImage = generateDynamicImage();
  const finalImageAlt = imageAlt || `${title} - ToolsML AI Tools Directory`;

  // Extract primary keyword for additional optimization
  const primaryKeyword = title.split(' ')[0];

  return (
    <Helmet>
      {/* Enhanced Open Graph Tags */}
      <meta property="og:type" content={type} />
      <meta property="og:url" content={fullUrl} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={ogImage} />
      <meta property="og:image:secure_url" content={ogImage} />
      <meta property="og:image:width" content={imageWidth.toString()} />
      <meta property="og:image:height" content={imageHeight.toString()} />
      <meta property="og:image:alt" content={finalImageAlt} />
      <meta property="og:image:type" content="image/jpeg" />
      <meta property="og:site_name" content="ToolsML" />
      <meta property="og:locale" content="en_US" />
      <meta property="og:locale:alternate" content="en_GB" />
      
      {/* Article-specific tags */}
      {type === 'article' && (
        <>
          {publishedTime && <meta property="article:published_time" content={publishedTime} />}
          {modifiedTime && <meta property="article:modified_time" content={modifiedTime} />}
          {author && <meta property="article:author" content={author} />}
          {section && <meta property="article:section" content={section} />}
          {tags.map((tag) => (
            <meta key={tag} property="article:tag" content={tag} />
          ))}
        </>
      )}

      {/* Product-specific tags */}
      {(type === 'product' || tool) && tool && (
        <>
          <meta property="product:price:amount" content={tool.pricing === 'Free' ? '0' : undefined} />
          <meta property="product:price:currency" content="USD" />
          <meta property="product:availability" content="in stock" />
          <meta property="product:condition" content="new" />
          <meta property="product:brand" content={tool.company} />
          <meta property="product:category" content={tool.category} />
        </>
      )}

      {/* Enhanced Twitter Card Tags */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@toolsml" />
      <meta name="twitter:creator" content="@toolsml" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={ogImage} />
      <meta name="twitter:image:alt" content={finalImageAlt} />
      <meta name="twitter:domain" content="ai-toolsml.lovable.app" />
      <meta name="twitter:url" content={fullUrl} />
      
      {/* Twitter App Card (for mobile deep linking) */}
      <meta name="twitter:app:name:iphone" content="ToolsML" />
      <meta name="twitter:app:name:ipad" content="ToolsML" />
      <meta name="twitter:app:name:googleplay" content="ToolsML" />
      
      {/* Enhanced Facebook Tags */}
      <meta property="fb:app_id" content="your-facebook-app-id" />
      <meta property="fb:pages" content="your-facebook-page-id" />

      {/* LinkedIn Tags */}
      <meta property="og:see_also" content={`${baseUrl}/about`} />
      
      {/* Pinterest Tags */}
      <meta name="pinterest-rich-pin" content="true" />
      <meta property="og:description" content={description} />
      
      {/* Mobile App Tags */}
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      <meta name="apple-mobile-web-app-title" content="ToolsML" />
      <meta name="mobile-web-app-capable" content="yes" />
      
      {/* Additional SEO Meta Tags */}
      <meta name="news_keywords" content={tags.join(', ')} />
      <meta name="subject" content={primaryKeyword} />
      <meta name="abstract" content={description} />
      <meta name="topic" content="Artificial Intelligence Tools" />
      <meta name="summary" content={description} />
      <meta name="classification" content="Technology" />
      <meta name="designer" content="ToolsML Team" />
      <meta name="reply-to" content="contact@toolsml.com" />
      <meta name="owner" content="ToolsML" />
      <meta name="directory" content="submission" />
      <meta name="category" content="Technology" />
      <meta name="coverage" content="Worldwide" />
      <meta name="distribution" content="Global" />
      <meta name="rating" content="General" />
      
      {/* Geo Tags */}
      <meta name="geo.region" content="US" />
      <meta name="geo.placename" content="United States" />
      
      {/* Structured Data - Alternative Tags */}
      <meta itemProp="name" content={title} />
      <meta itemProp="description" content={description} />
      <meta itemProp="image" content={ogImage} />
    </Helmet>
  );
};

export default AdvancedMetaTags;